# Generated by Django 3.2.6 on 2023-03-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='update_by',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Supervisor'), ('M', 'Manager')], max_length=10),
        ),
    ]
